Issues Resolved
complexitybot/QuizBot pull request #4
Opened 2019-05-07 14:22 UTC by bully434

# Что сделано?
https://github.com/complexitybot/Quiz/issues/74
https://github.com/complexitybot/Quiz/issues/75
https://github.com/complexitybot/Quiz/issues/76
https://github.com/complexitybot/Quiz/issues/77
https://github.com/complexitybot/Quiz/issues/89
https://github.com/complexitybot/Quiz/issues/90
___

## Комментарии

2019-05-07 19:09 UTC, FunFunFine requested changes

2019-05-07 19:09 UTC, FunFunFine commented on QuizBot/QuizBotCore/Buttons & CallBacks/DialogMessages.cs
> +        public const string CheckTaskCorrect = "А ты прав!";
У бля, сорокина на тебя нет.
Вспомни регламент ЯТП того года -- глаголы в названиях только у методов и делегатов.
А тут не оно!111

2019-05-07 19:09 UTC, FunFunFine commented on QuizBot/QuizBotCore/Buttons & CallBacks/DialogMessages.cs
> +        public static readonly char[] Alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".ToCharArray();
`Enumerable.Range('A', 26).Select(x=>(char)x).ToArray();`
Так точно можно быть уверенным, что ты не пропустил букву.

2019-05-07 19:09 UTC, FunFunFine commented on QuizBot/QuizBotCore/Buttons & CallBacks/DialogMessages.cs
> +        public static readonly char[] Alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".ToCharArray();
ЕТО ТОБi НЕ ПiТОН

2019-05-07 19:09 UTC, FunFunFine commented on QuizBot/QuizBotCore/Buttons & CallBacks/DialogMessages.cs
> +        public static readonly string LevelCompleted = "Ты решил все задачки из этого уровня👌🏿\n" +
Пробел перед эможей ткни, приятнее будет глазу

2019-05-07 19:09 UTC, FunFunFine commented on QuizBot/QuizBotCore/Commands/CheckTaskCommand.cs
> +                    await client.SendTextMessageAsync(chat.Id, DialogMessages.CheckTaskCorrect);
Связка из  `IQuizService quizService, IUserRepository userRepository, ILogger logger` оч много раз передается, надо ее выделить в класс-хранилку. Решарпер так умеет:
Идешь к методу -- Refactor This -- Transform Parameters

2019-05-07 19:09 UTC, FunFunFine commented on QuizBot/QuizBotCore/Commands/SelectLevelCommand.cs
> +            var closedLevels = allLevels.Select(x => x.Description).Except(availableLevels.Select(x => x.Description));
У левелов может быть одинаковое описание вполне.
Ну, это бред малость, но лучше перестраховаться и по айди сравнивать.
Или определить Equals полностью

2019-05-07 19:09 UTC, FunFunFine commented on QuizBot/QuizBotCore/Commands/ShowTaskCommand.cs
> +            {
вот это все дело с ифами тянет на отдельный метод приватный здесь, `TryGetTask(userId, topicId, levelId, out var task)`, иначе сложно читать оч, не сразу понятно, что происходит.

2019-05-07 19:09 UTC, FunFunFine commented on QuizBot/QuizBotCore/Commands/ShowTaskCommand.cs
> +            {
Ооооооочень длинный метод. В контуре не похвалят за такое (хотя еще в каких командах смотря).
Постарайся выделить методы типа `BuildProgressBar` и подобные.

2019-05-07 19:09 UTC, FunFunFine commented on QuizBot/QuizBotCore/Commands/ShowTaskCommand.cs
> +            {
Декомпозиция, вспомнил, вот ее надо

2019-05-07 19:09 UTC, FunFunFine commented on QuizBot/QuizBotCore/Parser/MessageParser.cs
> +                var index = int.Parse(levelId);
Почему просто Parse? Доверяешь сообщениям пользователя?
Если не сможет здесь, то кинет ошибку, а трайкетчей у тебя нет, вылетит 500 и телеграм расстроится.
Лучше будет TryParse(id, out var index)

2019-05-07 19:09 UTC, FunFunFine commented on QuizBot/QuizRequestService/HintDTO.cs
> +        public string HintText;
Геттеры добавить нужно точно, поля простые считаются ПЛОХИМ КОДОМ (хз почему даже в дтошках, но так уж сложилось)

2019-05-08 13:11 UTC, FunFunFine approved these changes

2019-05-09 09:16 UTC, bully434 commented
Добавлены тесты на TelegramStateMachine

2019-05-09 11:53 UTC, FunFunFine approved these changes

2019-05-09 11:53 UTC, FunFunFine commented on QuizBot/QuizBotCoreTests/TelegramStateMachineTests.cs
> +            state.GetType().Should().Be(typeof(TopicSelectionState));
`state.Should().BeOfType<TopicSelectionState>()`

2019-05-09 13:14 UTC, merged